CREATE TABLE IF NOT EXISTS contribution_opportunities (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    announcement_id INT NOT NULL,
    opportunity_type VARCHAR(40) NOT NULL,
    registration_deadline DATETIME NULL,
    capacity INT NULL,
    required_skills TEXT NULL,
    available_roles TEXT NULL,
    instructions TEXT NULL,
    objectives TEXT NULL,
    target_date DATE NULL,
    support_types TEXT NULL,
    target_quantity VARCHAR(120) NULL,
    contact_instructions TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Open',
    created_by VARCHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_contribution_opportunity_announcement (announcement_id),
    INDEX idx_contribution_opportunity_type_status (opportunity_type, status),
    INDEX idx_contribution_opportunity_deadline (registration_deadline),
    FOREIGN KEY (announcement_id) REFERENCES announcements(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS contribution_submissions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    opportunity_id BIGINT NOT NULL,
    announcement_id INT NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    submission_type VARCHAR(40) NOT NULL,
    availability VARCHAR(255) NULL,
    preferred_role VARCHAR(255) NULL,
    skills TEXT NULL,
    contact_info VARCHAR(255) NULL,
    description TEXT NULL,
    quantity DECIMAL(12,2) NULL,
    unit VARCHAR(80) NULL,
    estimated_value DECIMAL(14,2) NULL,
    proposed_date DATE NULL,
    message TEXT NULL,
    evidence_url LONGTEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Registered',
    assigned_role VARCHAR(255) NULL,
    attendance_status VARCHAR(30) NULL,
    actual_hours DECIMAL(10,2) NULL,
    fulfilled_quantity DECIMAL(12,2) NULL,
    fulfilled_value DECIMAL(14,2) NULL,
    admin_notes TEXT NULL,
    verified_by VARCHAR(36) NULL,
    verified_at DATETIME NULL,
    withdrawn_at DATETIME NULL,
    contribution_id INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_contribution_submission_user_opportunity (opportunity_id, user_id),
    INDEX idx_contribution_submission_type_status (submission_type, status),
    INDEX idx_contribution_submission_user (user_id, status),
    INDEX idx_contribution_submission_announcement (announcement_id),
    FOREIGN KEY (opportunity_id) REFERENCES contribution_opportunities(id) ON DELETE CASCADE,
    FOREIGN KEY (announcement_id) REFERENCES announcements(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (contribution_id) REFERENCES donations(id) ON DELETE SET NULL
);

ALTER TABLE donations ADD COLUMN source_module VARCHAR(40) NULL AFTER supporting_information;
ALTER TABLE donations ADD COLUMN source_record_id BIGINT NULL AFTER source_module;
ALTER TABLE donations ADD UNIQUE INDEX uq_donations_source_record (source_module, source_record_id);
