import { createContext, ReactNode, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { API_URL, readApiResponse, resolveAssetUrl } from "@/lib/api";
import { COURSE_OPTIONS, normalizeCourseOptions, type CourseOption } from "@/lib/courseCatalog";

export interface SystemSettings {
  id: number;
  systemName: string;
  systemShortName: string;
  institutionName: string;
  institutionAddress: string;
  institutionEmail: string;
  institutionContact: string;
  websiteUrl: string;
  footerCopyrightText: string;
  logoPath: string;
  loginLogoPath: string;
  faviconPath: string;
  loginBackgroundPath: string;
  loginBackgrounds: string[];
  loginSlideshowEnabled: boolean;
  primaryColor: string;
  secondaryColor: string;
  sidebarColor: string;
  headerColor: string;
  buttonColor: string;
  cardColor: string;
  welcomeMessage: string;
  loginSubtitle: string;
  aboutContent: string;
  mission: string;
  vision: string;
  history: string;
  facebookLink: string;
  twitterLink: string;
  instagramLink: string;
  programs: CourseOption[];
  themeMode: "light" | "dark" | "auto" | "custom";
  updatedAt: string | null;
}

export const DEFAULT_SYSTEM_SETTINGS: SystemSettings = {
  id: 1,
  systemName: "Alumni Management Portal",
  systemShortName: "Alumni Portal",
  institutionName: "Your Institution",
  institutionAddress: "",
  institutionEmail: "",
  institutionContact: "",
  websiteUrl: "",
  footerCopyrightText: "Generated by Alumni Management System",
  logoPath: "",
  loginLogoPath: "",
  faviconPath: "",
  loginBackgroundPath: "",
  loginBackgrounds: [],
  loginSlideshowEnabled: false,
  primaryColor: "#550000",
  secondaryColor: "#3f3f46",
  sidebarColor: "#383838",
  headerColor: "#550000",
  buttonColor: "#550000",
  cardColor: "#f7f7f7",
  welcomeMessage: "Welcome to the Alumni Management Portal",
  loginSubtitle: "Sign in using your alumni ID or official email.",
  aboutContent: "A centralized portal for alumni records, engagement, tracer studies, announcements, achievements, donations, and community updates.",
  mission: "Provide a reliable alumni platform that supports communication, graduate tracking, engagement, and institutional decision-making.",
  vision: "A connected alumni community that helps the institution improve programs, services, and graduate outcomes.",
  history: "",
  facebookLink: "",
  twitterLink: "",
  instagramLink: "",
  programs: COURSE_OPTIONS,
  themeMode: "light",
  updatedAt: null,
};

export const SYSTEM_SETTINGS_CACHE_KEY = "system_branding_settings";

interface SystemSettingsContextValue {
  settings: SystemSettings;
  loading: boolean;
  refreshSettings: () => Promise<SystemSettings>;
}

const SystemSettingsContext = createContext<SystemSettingsContextValue>({
  settings: DEFAULT_SYSTEM_SETTINGS,
  loading: true,
  refreshSettings: async () => DEFAULT_SYSTEM_SETTINGS,
});

const hexToHslParts = (hex: string) => {
  const normalized = /^#[0-9a-fA-F]{6}$/.test(hex) ? hex : "#550000";
  const r = parseInt(normalized.slice(1, 3), 16) / 255;
  const g = parseInt(normalized.slice(3, 5), 16) / 255;
  const b = parseInt(normalized.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const delta = max - min;
    s = l > 0.5 ? delta / (2 - max - min) : delta / (max + min);
    if (max === r) h = (g - b) / delta + (g < b ? 6 : 0);
    if (max === g) h = (b - r) / delta + 2;
    if (max === b) h = (r - g) / delta + 4;
    h /= 6;
  }

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
};

const normalizeSettings = (value: Partial<SystemSettings> | null | undefined): SystemSettings => ({
  ...DEFAULT_SYSTEM_SETTINGS,
  ...(value || {}),
  loginBackgrounds: Array.isArray(value?.loginBackgrounds) ? value.loginBackgrounds : [],
  programs: normalizeCourseOptions(value?.programs),
  themeMode: ["light", "dark", "auto", "custom"].includes(String(value?.themeMode))
    ? value?.themeMode as SystemSettings["themeMode"]
    : DEFAULT_SYSTEM_SETTINGS.themeMode,
});

const setFavicon = (href: string) => {
  if (!href) return;
  const resolvedHref = resolveAssetUrl(href) || href;
  let link = document.querySelector<HTMLLinkElement>("link[rel='icon']");
  if (!link) {
    link = document.createElement("link");
    link.rel = "icon";
    document.head.appendChild(link);
  }
  link.href = resolvedHref;
};

const applySystemSettings = (settings: SystemSettings) => {
  const root = document.documentElement;
  const darkMode = settings.themeMode === "dark";

  root.style.setProperty("--primary", hexToHslParts(settings.primaryColor));
  root.style.setProperty("--accent", hexToHslParts(settings.primaryColor));
  root.style.setProperty("--secondary", hexToHslParts(settings.secondaryColor));
  root.style.setProperty("--sidebar-background", hexToHslParts(settings.sidebarColor));
  root.style.setProperty("--sidebar-active", hexToHslParts(settings.buttonColor));
  root.style.setProperty("--header-background", hexToHslParts(settings.headerColor));
  root.style.setProperty("--ring", hexToHslParts(settings.primaryColor));
  root.style.setProperty("--card-accent", hexToHslParts(settings.cardColor));

  if (darkMode) {
    root.style.setProperty("--background", "0 0% 10%");
    root.style.setProperty("--foreground", "0 0% 96%");
    root.style.setProperty("--card", "0 0% 14%");
    root.style.setProperty("--card-foreground", "0 0% 96%");
    root.style.setProperty("--muted", "0 0% 20%");
    root.style.setProperty("--muted-foreground", "0 0% 78%");
    root.style.setProperty("--border", "0 0% 28%");
  } else {
    root.style.setProperty("--background", "0 0% 97%");
    root.style.setProperty("--foreground", "0 0% 15%");
    root.style.setProperty("--card", "0 0% 100%");
    root.style.setProperty("--card-foreground", "0 0% 15%");
    root.style.setProperty("--muted", "0 0% 93%");
    root.style.setProperty("--muted-foreground", "0 0% 40%");
    root.style.setProperty("--border", "0 0% 82%");
  }

  document.title = settings.systemShortName || settings.systemName;
  localStorage.setItem(SYSTEM_SETTINGS_CACHE_KEY, JSON.stringify(settings));
  if (settings.faviconPath) setFavicon(settings.faviconPath);
};

export function SystemSettingsProvider({ children }: { children: ReactNode }) {
  const [settings, setSettings] = useState<SystemSettings>(DEFAULT_SYSTEM_SETTINGS);
  const [loading, setLoading] = useState(true);

  const refreshSettings = useCallback(async () => {
    const response = await fetch(`${API_URL}/system-settings`);
    const data = normalizeSettings(await readApiResponse<SystemSettings>(response));
    setSettings(data);
    applySystemSettings(data);
    return data;
  }, []);

  useEffect(() => {
    let mounted = true;
    setLoading(true);
    refreshSettings()
      .catch(() => {
        if (mounted) applySystemSettings(DEFAULT_SYSTEM_SETTINGS);
      })
      .finally(() => {
        if (mounted) setLoading(false);
      });
    return () => {
      mounted = false;
    };
  }, [refreshSettings]);

  const value = useMemo(() => ({ settings, loading, refreshSettings }), [loading, refreshSettings, settings]);

  return (
    <SystemSettingsContext.Provider value={value}>
      {children}
    </SystemSettingsContext.Provider>
  );
}

export const useSystemSettings = () => useContext(SystemSettingsContext);

